/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["healthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Регистрация нового пользователя */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Авторизация пользователя */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Обновление access токена */
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Выход из системы */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получение информации о текущем пользователе */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить список всех пользователей */
        get: operations["listUsers"];
        put?: never;
        /** Добавить нового пользователя */
        post: operations["createUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить профиль конкретного пользователя */
        get: operations["getUserById"];
        /** Обновить профиль пользователя */
        put: operations["updateUser"];
        post?: never;
        /** Удалить пользователя */
        delete: operations["deleteUser"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить персональное расписание работы */
        get: operations["getUserSchedule"];
        /** Изменить расписание работы */
        put: operations["updateUserSchedule"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Поиск по имени / email */
        get: operations["searchUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Начать рабочую сессию */
        post: operations["startSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Взять паузу (обед, кофе и т.д.) */
        post: operations["pauseSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Возобновить работу после паузы */
        post: operations["resumeSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/end": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Завершить рабочий день */
        post: operations["endSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{userId}/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Текущая сессия сотрудника (если активна) */
        get: operations["getTodaySession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{userId}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** История всех сессий пользователя */
        get: operations["getSessionHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/statistics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Сводная статистика (агрегация по всем пользователям или отделам) */
        get: operations["getStatistics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/departments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить список всех отделов */
        get: operations["listDepartments"];
        put?: never;
        /** Создать новый отдел */
        post: operations["createDepartment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/departments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить информацию о конкретном отделе */
        get: operations["getDepartmentById"];
        /** Обновить данные отдела */
        put: operations["updateDepartment"];
        post?: never;
        /** Удалить отдел */
        delete: operations["deleteDepartment"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/departments/{id}/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить список сотрудников отдела */
        get: operations["getDepartmentUsers"];
        /** Добавить или удалить сотрудников из отдела */
        put: operations["updateDepartmentUsers"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/positions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить список всех должностей */
        get: operations["listPositions"];
        put?: never;
        /** Создать новую должность */
        post: operations["createPosition"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/positions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить информацию о конкретной должности */
        get: operations["getPositionById"];
        /** Обновить данные должности */
        put: operations["updatePosition"];
        post?: never;
        /** Удалить должность */
        delete: operations["deletePosition"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/statistics/absences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Список отсутствий и длительных перерывов по сотрудникам за период */
        get: operations["getAbsences"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/statistics/top-engagements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Топ сотрудников по вовлеченности */
        get: operations["getTopEngagements"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/statistics/department-details": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Детальная статистика по отделу за выбранный период */
        get: operations["getDepartmentDetails"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/statistics/daily-engagement": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Средняя вовлеченность в день по работникам отдела */
        get: operations["getDailyEngagement"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegisterRequest: {
            /** @example Иван Иванов */
            name: string;
            /**
             * Format: email
             * @example user@example.com
             */
            email: string;
            /** @example password123 */
            password: string;
            /**
             * Format: int64
             * @example 1
             */
            position_id?: number | null;
            /**
             * Format: int64
             * @example 1
             */
            role_id: number;
            /**
             * Format: int64
             * @example 1
             */
            department_id: number;
        };
        LoginRequest: {
            /**
             * Format: email
             * @example user@example.com
             */
            email: string;
            /** @example password123 */
            password: string;
        };
        RefreshRequest: {
            /** @example a1b2c3d4e5f6... */
            refresh_token: string;
        };
        LoginResponse: {
            /** @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9... */
            access_token?: string;
            /** @example a1b2c3d4e5f6... */
            refresh_token?: string;
            /**
             * @description Время жизни access токена в секундах
             * @example 900
             */
            expires_in?: number;
            user?: components["schemas"]["UserDTO"];
        };
        RefreshResponse: {
            /** @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9... */
            access_token?: string;
            /** @example 900 */
            expires_in?: number;
        };
        UserDTO: {
            /**
             * Format: int64
             * @example 1
             */
            id?: number;
            /** @example Иван Иванов */
            name?: string;
            /**
             * Format: email
             * @example user@example.com
             */
            email?: string;
            /** @example Разработчик */
            position?: string | null;
            /** @example admin */
            role?: string | null;
            /** @example IT отдел */
            department?: string | null;
            /**
             * Format: int64
             * @description Unix timestamp
             * @example 1640995200
             */
            created_at?: number;
            /**
             * Format: int64
             * @description Unix timestamp
             * @example 1640995200
             */
            updated_at?: number;
        };
        SuccessResponse: {
            /** @example Операция выполнена успешно */
            message?: string;
        };
        ErrorResponse: {
            /** @example Описание ошибки */
            error?: string;
        };
        CreateUserRequest: {
            /** @example Петр Сидоров */
            name: string;
            /**
             * Format: email
             * @example petr@example.com
             */
            email: string;
            /** @example password123 */
            password: string;
            /**
             * Format: int64
             * @example 2
             */
            position_id?: number | null;
            /**
             * Format: int64
             * @example 2
             */
            role_id: number;
            /**
             * Format: int64
             * @example 1
             */
            department_id: number;
        };
        UpdateUserRequest: {
            /** @example Петр Петрович Сидоров */
            name?: string;
            /**
             * Format: email
             * @example petr.new@example.com
             */
            email?: string;
            /**
             * Format: int64
             * @example 3
             */
            position_id?: number | null;
            /**
             * Format: int64
             * @example 1
             */
            role_id?: number;
            /**
             * Format: int64
             * @example 2
             */
            department_id?: number;
        };
        UserListResponse: {
            users?: components["schemas"]["UserDTO"][];
            /**
             * Format: int64
             * @description Общее количество пользователей
             * @example 42
             */
            total?: number;
            /**
             * @description Текущая страница
             * @example 1
             */
            page?: number;
            /**
             * @description Размер страницы
             * @example 20
             */
            page_size?: number;
            /**
             * @description Общее количество страниц
             * @example 3
             */
            total_pages?: number;
        };
        UserScheduleDTO: {
            /**
             * Format: int64
             * @example 1
             */
            user_id?: number;
            /** @example 09:00-18:00 */
            monday?: string | null;
            /** @example 09:00-18:00 */
            tuesday?: string | null;
            /** @example 09:00-18:00 */
            wednesday?: string | null;
            /** @example 09:00-18:00 */
            thursday?: string | null;
            /** @example 09:00-18:00 */
            friday?: string | null;
            /** @example Выходной */
            saturday?: string | null;
            /** @example Выходной */
            sunday?: string | null;
            /**
             * Format: int64
             * @description Unix timestamp
             * @example 1640995200
             */
            updated_at?: number;
        };
        UpdateScheduleRequest: {
            /** @example 10:00-19:00 */
            monday?: string | null;
            /** @example 10:00-19:00 */
            tuesday?: string | null;
            /** @example 10:00-19:00 */
            wednesday?: string | null;
            /** @example 10:00-19:00 */
            thursday?: string | null;
            /** @example 10:00-19:00 */
            friday?: string | null;
            /** @example Выходной */
            saturday?: string | null;
            /** @example Выходной */
            sunday?: string | null;
        };
        PauseSessionRequest: {
            /**
             * Format: int64
             * @example 1
             */
            session_id: number;
            /**
             * @description Причина паузы (обед, кофе и т.д.)
             * @example Обед
             */
            reason?: string | null;
        };
        ResumeSessionRequest: {
            /**
             * Format: int64
             * @example 1
             */
            session_id: number;
        };
        EndSessionRequest: {
            /**
             * Format: int64
             * @example 1
             */
            session_id: number;
        };
        SessionDTO: {
            /**
             * Format: int64
             * @example 1
             */
            id?: number;
            /**
             * Format: int64
             * @example 1
             */
            user_id?: number;
            /**
             * Format: int64
             * @description Unix timestamp
             * @example 1640995200
             */
            start_time?: number;
            /**
             * Format: int64
             * @description Unix timestamp
             * @example 1641081600
             */
            end_time?: number | null;
            /**
             * Format: int64
             * @description Продолжительность в секундах
             * @example 28800
             */
            total_duration?: number | null;
            /**
             * Format: int64
             * @description Текущая продолжительность сессии в секундах (только для today endpoint, без учета перерывов)
             * @example 14400
             */
            current_duration?: number | null;
            /** @example true */
            is_active?: boolean;
            breaks?: components["schemas"]["BreakDTO"][] | null;
            /**
             * Format: int64
             * @description Unix timestamp
             * @example 1640995200
             */
            created_at?: number;
        };
        BreakDTO: {
            /**
             * Format: int64
             * @example 1
             */
            id?: number;
            /**
             * Format: int64
             * @example 1
             */
            session_id?: number;
            /** @example Обед */
            reason?: string | null;
            /**
             * Format: int64
             * @description Unix timestamp
             * @example 1640995200
             */
            start_time?: number;
            /**
             * Format: int64
             * @description Unix timestamp
             * @example 1641081600
             */
            end_time?: number | null;
            /**
             * Format: int64
             * @description Продолжительность в секундах
             * @example 3600
             */
            duration?: number | null;
            /** @example false */
            is_active?: boolean;
            /**
             * Format: int64
             * @description Unix timestamp
             * @example 1640995200
             */
            created_at?: number;
        };
        SessionHistoryResponse: {
            sessions?: components["schemas"]["SessionDTO"][];
            /**
             * @description Количество сессий
             * @example 10
             */
            total?: number;
        };
        StatisticsResponse: {
            /**
             * @description Среднее время начала работы
             * @example 09:30:00
             */
            avg_start_time?: string;
            /**
             * @description Среднее время окончания работы
             * @example 18:15:00
             */
            avg_end_time?: string;
            /**
             * Format: int64
             * @description Средняя продолжительность работы в секундах
             * @example 28800
             */
            avg_duration?: number;
            /**
             * Format: float
             * @description Процент присутствия
             * @example 85.5
             */
            presence_percent?: number;
            /**
             * @description Количество опозданий
             * @example 5
             */
            late_arrivals?: number;
            /**
             * @description Количество ранних уходов
             * @example 3
             */
            early_leaves?: number;
            /**
             * @description Общее количество завершенных сессий
             * @example 120
             */
            total_sessions?: number;
            /**
             * @description Количество уникальных пользователей
             * @example 25
             */
            total_users?: number;
        };
        DepartmentDTO: {
            /**
             * Format: int64
             * @example 1
             */
            id?: number;
            /** @example IT отдел */
            name?: string;
            /** @example Отдел информационных технологий */
            description?: string | null;
            /** @example Иван Иванов */
            manager_name?: string | null;
            /** @example ivan.ivanov@example.com */
            manager_email?: string | null;
            /**
             * @description Количество сотрудников в отделе
             * @example 15
             */
            users_count?: number;
            /**
             * Format: int64
             * @description Unix timestamp
             * @example 1640995200
             */
            created_at?: number;
            /**
             * Format: int64
             * @description Unix timestamp
             * @example 1640995200
             */
            updated_at?: number;
        };
        CreateDepartmentRequest: {
            /** @example IT отдел */
            name: string;
            /** @example Отдел информационных технологий */
            description?: string | null;
            /**
             * Format: int64
             * @example 5
             */
            manager_id?: number | null;
        };
        UpdateDepartmentRequest: {
            /** @example IT отдел */
            name?: string;
            /** @example Отдел информационных технологий */
            description?: string | null;
            /**
             * Format: int64
             * @example 5
             */
            manager_id?: number | null;
        };
        DepartmentListResponse: {
            departments?: components["schemas"]["DepartmentDTO"][];
            /**
             * Format: int64
             * @example 100
             */
            total?: number;
            /** @example 1 */
            page?: number;
            /** @example 20 */
            page_size?: number;
            /** @example 5 */
            total_pages?: number;
        };
        DepartmentUsersRequest: {
            /**
             * @example [
             *       1,
             *       2,
             *       3
             *     ]
             */
            user_ids: number[];
        };
        DepartmentUsersResponse: {
            users?: components["schemas"]["UserDTO"][];
            /** @example 10 */
            total?: number;
        };
        PositionDTO: {
            /**
             * Format: int64
             * @example 1
             */
            id?: number;
            /** @example Senior Developer */
            title?: string;
            /** @example Старший разработчик */
            description?: string | null;
            /**
             * Format: int64
             * @description Unix timestamp
             * @example 1640995200
             */
            created_at?: number;
        };
        PositionListResponse: {
            positions?: components["schemas"]["PositionDTO"][];
        };
        CreatePositionRequest: {
            /** @example Senior Developer */
            title: string;
            /** @example Старший разработчик */
            description?: string | null;
        };
        UpdatePositionRequest: {
            /** @example Senior Developer */
            title?: string;
            /** @example Старший разработчик */
            description?: string | null;
        };
        AbsenceItemDTO: {
            /**
             * Format: int64
             * @example 1
             */
            user_id?: number;
            /** @example Иван Иванов */
            user_name?: string;
            /**
             * @example absence
             * @enum {string}
             */
            type?: "absence" | "long_break";
            /**
             * Format: int64
             * @description Unix timestamp
             * @example 1640995200
             */
            start_date?: number;
            /**
             * Format: int64
             * @description Unix timestamp
             * @example 1641081600
             */
            end_date?: number | null;
            /** @example Больничный */
            reason?: string;
            /**
             * Format: int64
             * @description Длительность в секундах (только для long_break)
             * @example 3600
             */
            duration?: number | null;
        };
        AbsencesResponse: {
            items?: components["schemas"]["AbsenceItemDTO"][];
            /** @example 15 */
            total?: number;
        };
        TopPerformerDTO: {
            /**
             * Format: int64
             * @example 1
             */
            user_id?: number;
            /** @example Иван Иванов */
            user_name?: string;
            /**
             * Format: int64
             * @example 2
             */
            department_id?: number | null;
            /** @example IT отдел */
            department_name?: string | null;
            /**
             * Format: float
             * @description Вовлеченность (0-1, где 1 - максимальная вовлеченность)
             * @example 0.85
             */
            engagement?: number;
            /**
             * Format: float
             * @description Среднее рабочее время в часах
             * @example 8.5
             */
            avg_work_time?: number;
        };
        TopPerformersResponse: {
            performers?: components["schemas"]["TopPerformerDTO"][];
            /** @example 10 */
            total?: number;
        };
        AverageWorktimeResponse: {
            /**
             * Format: int64
             * @example 2
             */
            department_id?: number;
            /** @example IT отдел */
            department_name?: string | null;
            /**
             * @example month
             * @enum {string}
             */
            period?: "week" | "month" | "year";
            /**
             * Format: float
             * @description Среднее рабочее время в часах
             * @example 7.5
             */
            avg_hours?: number;
        };
        DepartmentDetailsResponse: {
            /**
             * Format: int64
             * @example 2
             */
            department_id?: number;
            /** @example IT отдел */
            department_name?: string | null;
            /**
             * Format: date
             * @description Начальная дата (формат YYYY-MM-DD)
             * @example 2025-10-01
             */
            from_date?: string;
            /**
             * Format: date
             * @description Конечная дата (формат YYYY-MM-DD)
             * @example 2025-10-31
             */
            to_date?: string;
            /**
             * Format: float
             * @description Среднее рабочее время в часах
             * @example 7.5
             */
            avg_worktime_hours?: number;
            /**
             * Format: float
             * @description Среднее время перерыва в минутах
             * @example 45.5
             */
            avg_break_minutes?: number;
            /**
             * @description Количество сотрудников в отделе
             * @example 15
             */
            employees_count?: number;
            /**
             * @description Количество отклонений от графика (начал позже или закончил раньше на 30+ минут)
             * @example 5
             */
            schedule_deviations?: number;
            /**
             * @description Общее количество рабочих сессий за период
             * @example 120
             */
            total_sessions?: number;
        };
        DailyEngagementItem: {
            /**
             * Format: date
             * @description Дата (формат YYYY-MM-DD)
             * @example 2025-10-01
             */
            date?: string;
            /**
             * Format: float
             * @description Средняя вовлеченность за день (0-1)
             * @example 0.85
             */
            engagement?: number;
        };
        DailyEngagementResponse: {
            /** @description Массив данных по дням */
            items?: components["schemas"]["DailyEngagementItem"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status?: string;
                    };
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Пользователь успешно зарегистрирован */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Ошибка валидации */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Пользователь уже существует */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Успешная авторизация */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Неверные учетные данные */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Токен успешно обновлен */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshResponse"];
                };
            };
            /** @description Неверный refresh token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    refresh_token: string;
                };
            };
        };
        responses: {
            /** @description Успешный выход */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"];
                };
            };
            /** @description Неавторизованный запрос */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Информация о пользователе */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDTO"];
                };
            };
            /** @description Неавторизованный запрос */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listUsers: {
        parameters: {
            query?: {
                /** @description Номер страницы */
                page?: number;
                /** @description Количество элементов на странице */
                page_size?: number;
                /** @description Фильтр по отделу */
                department_id?: number;
                /** @description Фильтр по должности */
                position_id?: number;
                /** @description Фильтр по роли */
                role_id?: number;
                /** @description Поиск по имени или email */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список пользователей */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserListResponse"];
                };
            };
            /** @description Неавторизованный запрос */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserRequest"];
            };
        };
        responses: {
            /** @description Пользователь успешно создан */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDTO"];
                };
            };
            /** @description Ошибка валидации */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Неавторизованный запрос */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getUserById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID пользователя */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Профиль пользователя */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDTO"];
                };
            };
            /** @description Неавторизованный запрос */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Пользователь не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID пользователя */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserRequest"];
            };
        };
        responses: {
            /** @description Профиль успешно обновлен */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDTO"];
                };
            };
            /** @description Ошибка валидации */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Неавторизованный запрос */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Пользователь не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deleteUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID пользователя */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Пользователь успешно удален */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"];
                };
            };
            /** @description Неавторизованный запрос */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Пользователь не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getUserSchedule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID пользователя */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Расписание пользователя */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserScheduleDTO"];
                };
            };
            /** @description Неавторизованный запрос */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Пользователь не найден или расписание не найдено */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateUserSchedule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID пользователя */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateScheduleRequest"];
            };
        };
        responses: {
            /** @description Расписание успешно обновлено */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserScheduleDTO"];
                };
            };
            /** @description Ошибка валидации */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Неавторизованный запрос */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Пользователь не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    searchUsers: {
        parameters: {
            query: {
                /** @description Поисковый запрос */
                query: string;
                /** @description Максимальное количество результатов */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Результаты поиска */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        users?: components["schemas"]["UserDTO"][];
                    };
                };
            };
            /** @description Неавторизованный запрос */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    startSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Сессия успешно начата */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"];
                };
            };
            /** @description Ошибка валидации */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Неавторизованный запрос */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    pauseSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PauseSessionRequest"];
            };
        };
        responses: {
            /** @description Пауза успешно начата */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"];
                };
            };
            /** @description Ошибка валидации */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Неавторизованный запрос */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    resumeSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResumeSessionRequest"];
            };
        };
        responses: {
            /** @description Работа успешно возобновлена */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDTO"];
                };
            };
            /** @description Ошибка валидации */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Неавторизованный запрос */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    endSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EndSessionRequest"];
            };
        };
        responses: {
            /** @description Сессия успешно завершена */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDTO"];
                };
            };
            /** @description Ошибка валидации */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Неавторизованный запрос */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getTodaySession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID пользователя */
                userId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Текущая сессия (может быть null, если сессия не найдена) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDTO"];
                };
            };
            /** @description Неавторизованный запрос */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getSessionHistory: {
        parameters: {
            query: {
                /** @description Начальная дата (YYYY-MM-DD) */
                from: string;
                /** @description Конечная дата (YYYY-MM-DD) */
                to: string;
            };
            header?: never;
            path: {
                /** @description ID пользователя */
                userId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description История сессий */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionHistoryResponse"];
                };
            };
            /** @description Неавторизованный запрос */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getStatistics: {
        parameters: {
            query: {
                /** @description Период статистики */
                period: "day" | "week" | "month";
                /** @description Фильтр по отделу (опционально) */
                department_id?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Статистика */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatisticsResponse"];
                };
            };
            /** @description Ошибка валидации */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Неавторизованный запрос */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listDepartments: {
        parameters: {
            query?: {
                /** @description Номер страницы */
                page?: number;
                /** @description Количество элементов на странице */
                page_size?: number;
                /** @description Фильтр по руководителю */
                manager_id?: number;
                /** @description Поиск по названию отдела */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список отделов */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DepartmentListResponse"];
                };
            };
            /** @description Неавторизованный запрос */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createDepartment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDepartmentRequest"];
            };
        };
        responses: {
            /** @description Отдел успешно создан */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DepartmentDTO"];
                };
            };
            /** @description Ошибка валидации */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Неавторизованный запрос */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getDepartmentById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID отдела */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Информация об отделе */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DepartmentDTO"];
                };
            };
            /** @description Неавторизованный запрос */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Отдел не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateDepartment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID отдела */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateDepartmentRequest"];
            };
        };
        responses: {
            /** @description Отдел успешно обновлен */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DepartmentDTO"];
                };
            };
            /** @description Ошибка валидации */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Неавторизованный запрос */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Отдел не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deleteDepartment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID отдела */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Отдел успешно удален */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"];
                };
            };
            /** @description Неавторизованный запрос */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Отдел не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getDepartmentUsers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID отдела */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список сотрудников отдела */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DepartmentUsersResponse"];
                };
            };
            /** @description Неавторизованный запрос */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Отдел не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateDepartmentUsers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID отдела */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DepartmentUsersRequest"];
            };
        };
        responses: {
            /** @description Список сотрудников отдела успешно обновлен */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DepartmentUsersResponse"];
                };
            };
            /** @description Ошибка валидации */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Неавторизованный запрос */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Отдел не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listPositions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список должностей */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PositionListResponse"];
                };
            };
            /** @description Неавторизованный запрос */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createPosition: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePositionRequest"];
            };
        };
        responses: {
            /** @description Должность успешно создана */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PositionDTO"];
                };
            };
            /** @description Ошибка валидации */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Неавторизованный запрос */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Должность с таким названием уже существует */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getPositionById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID должности */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Информация о должности */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PositionDTO"];
                };
            };
            /** @description Неавторизованный запрос */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Должность не найдена */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updatePosition: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID должности */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePositionRequest"];
            };
        };
        responses: {
            /** @description Должность успешно обновлена */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PositionDTO"];
                };
            };
            /** @description Ошибка валидации */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Неавторизованный запрос */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Должность не найдена */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Должность с таким названием уже существует */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deletePosition: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID должности */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Должность успешно удалена */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"];
                };
            };
            /** @description Неавторизованный запрос */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Должность не найдена */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getAbsences: {
        parameters: {
            query?: {
                /** @description Период статистики */
                period?: "week" | "month" | "year";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список отсутствий и перерывов */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AbsencesResponse"];
                };
            };
            /** @description Неавторизованный запрос */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getTopEngagements: {
        parameters: {
            query?: {
                /** @description Количество сотрудников в топе */
                limit?: number;
                /** @description Порядок сортировки (desc - лучшие, asc - худшие) */
                order?: "asc" | "desc";
                /** @description Фильтр по отделу (опционально) */
                departmentId?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список топ сотрудников */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopPerformersResponse"];
                };
            };
            /** @description Неавторизованный запрос */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getDepartmentDetails: {
        parameters: {
            query: {
                /** @description ID отдела (опционально, если не указан - данные по всем отделам) */
                departmentId?: number;
                /**
                 * @description Начальная дата (формат YYYY-MM-DD)
                 * @example 2025-10-01
                 */
                from: string;
                /**
                 * @description Конечная дата (формат YYYY-MM-DD)
                 * @example 2025-10-31
                 */
                to: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Детальная статистика по отделу */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DepartmentDetailsResponse"];
                };
            };
            /** @description Ошибка валидации */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Неавторизованный запрос */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Отдел не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getDailyEngagement: {
        parameters: {
            query: {
                /** @description ID отдела (опционально, если не указан - данные по всем отделам) */
                departmentId?: number;
                /**
                 * @description Начальная дата (формат YYYY-MM-DD)
                 * @example 2025-10-01
                 */
                from: string;
                /**
                 * @description Конечная дата (формат YYYY-MM-DD)
                 * @example 2025-10-31
                 */
                to: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Средняя вовлеченность по дням */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyEngagementResponse"];
                };
            };
            /** @description Ошибка валидации */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Неавторизованный запрос */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Отдел не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
